

let   help              = exports.help              = ['','help me','help','please help',"please help me","what can you do?","what can you do"],
      whatIsYourName    = exports.whatIsYourName    = ["","what's your name","what is your name","name"],
      whoAreYou         = exports.whoAreYou         = ["","who are you"],
      howAreYou         = exports.howAreYou         = ["",'how are you','how are you doing'],
      hello             = exports.hello             = ["","hello","hi","hallo","ola","hey there"],
      music             = exports.music             = ["","music","play music","play some music"],
      stopMusic         = exports.stopMusic         = ["",'stop music','music stop'],
      iAmFine           = exports.iAmFine           = ["","i'm fine","i'm good","i am fine","i am good"],
      tellMeAJoke       = exports.tellMeAJoke       = ["","tell me a joke","joke"],
      whoIsYourCreator  = exports.whoIsYourCreator  = ["","who is your creator","who build you","who created you","who created you?"],
      whoIsVoxny        = exports.whoIsVoxny        = ["","who is voxny","who is jessica"],
      activatePowerMode = exports.activatePowerMode = ["","activate power mode","power mode"],
      time              = exports.time              = ["","time","what's the time","what is the time","tell me the time","what time is it"],
      fua               = exports.FUA               = ["fuck you"],
      ba                = exports.BA                = ["bitch"],
      commands          = exports.commands          = ["","commands","show commands","display commands"],
      commandsDisable   = exports.commandsDisable   = ["","disable commands","commands-"],
      sing              = exports.singing           = ["","sing for me","sing"],
      speakGerman       = exports.speakGerman       = ["","speak german"],
      whatEver          = exports.whatEver          = ["","whatever"],
      howOld            = exports.howOld            = ["","how old are you","how old are you?"]

let theCommands = [
  help,
  whatIsYourName,
  whoAreYou,
  howAreYou,
  hello,
  music,
  stopMusic,
  iAmFine,
  tellMeAJoke,
  whoIsYourCreator,
  whoIsVoxny,
  activatePowerMode,
  time,
  fua,
  ba,
  commands,
  commandsDisable,
  sing,
  speakGerman,
  whatEver,
  howOld,
]

exports.allcommands = theCommands.toString()
